# BTF Processing Configuration
# ===========================
# This configuration file defines parameters for processing BTF files on HPC clusters.

# Input/Output Directories
input_dir: "./input"                    # Directory containing BTF files
output_dir: "./output"                  # Directory for processed tiles

# Processing Parameters
tile_size: 2048                         # Size of each tile (pixels)
green_channel: 1                        # Index of green channel (0=Red, 1=Green, 2=Blue)

# Logging Configuration
log_level: "INFO"                       # Logging level (DEBUG, INFO, WARNING, ERROR)
log_file: "btf_processing.log"          # Log file name

# Advanced Parameters (optional)
# These can be overridden via command line or environment variables

# Memory management
max_memory_gb: 60                       # Maximum memory usage in GB
chunk_size: 1024                        # Chunk size for processing

# Corrupted OME workaround
corrupted_ome_workaround: false         # Set to true for files with corrupted OME metadata

# File handling
file_patterns:                          # File patterns to process
  - "*.btf"
  - "*.ome.btf"

# Output organization
create_subdirs: true                    # Create subdirectories for each input file
preserve_structure: true                # Preserve original directory structure

# Quality control
validate_tiles: true                    # Validate generated tiles
check_file_integrity: true             # Check file integrity after processing

# Performance tuning
parallel_processing: false              # Enable parallel processing (experimental)
num_workers: 4                         # Number of worker processes

# HPC-specific settings
job_timeout: 86400                     # Job timeout in seconds (24 hours)
memory_per_core: 8                     # Memory per CPU core in GB
